# Utilisez l'image officielle PostgreSQL
FROM postgres:latest

# Définissez les variables d'environnement pour la base de données
ENV POSTGRES_DB=your_db_name
ENV POSTGRES_USER=your_db_user
ENV POSTGRES_PASSWORD=your_db_password

# Exposez le port sur lequel PostgreSQL écoutera (par défaut : 5432)
EXPOSE 5432
