# Dockerfile de frontend
FROM postgres:latest

# Définisser les variables d'environnement pour la base de données
ENV POSTGRES_DB=StorageDB
ENV POSTGRES_USER=EmmaDB
ENV POSTGRES_PASSWORD=1234STORAge!

# Exposer le port sur lequel PostgreSQL écoutera (par défaut : 5432)
EXPOSE 5432
