# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: STORAgeDB
      POSTGRES_USER: EmmaDB
      POSTGRES_PASSWORD: 1234STORAge!
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
      

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://EmmaDB:1234STORAge!@postgres:5432/STORAgeDB

volumes:
  postgres-data:
